<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Model;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Venda extends \Application\Model\Venda implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array('nome_vendedor' => NULL, 'nome' => NULL, 'cpfcnpj' => NULL, 'endereco' => NULL, 'cidade' => NULL, 'data_cadastro' => NULL, 'data_para_entrega' => NULL, 'nota_fiscal' => NULL, 'tipo_nf' => NULL, 'pagamento' => NULL, 'forma_pagamento' => NULL, 'descricao_outra_forma_pagamento' => NULL, 'telefone' => NULL, 'contato' => NULL, 'urgente' => NULL, 'envio' => NULL, 'endereco_entrega' => NULL, 'obs' => NULL, 'local_entrega' => NULL, 'ja_aberto' => NULL, 'carga' => NULL, 'produtos' => NULL, 'situacoes' => NULL, 'situacao' => NULL);



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {
        unset($this->nome_vendedor, $this->nome, $this->cpfcnpj, $this->endereco, $this->cidade, $this->data_cadastro, $this->data_para_entrega, $this->nota_fiscal, $this->tipo_nf, $this->pagamento, $this->forma_pagamento, $this->descricao_outra_forma_pagamento, $this->telefone, $this->contato, $this->urgente, $this->envio, $this->endereco_entrega, $this->obs, $this->local_entrega, $this->ja_aberto, $this->carga, $this->produtos, $this->situacoes, $this->situacao);

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * 
     * @param string $name
     */
    public function __get($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', array($name));

            return $this->$name;
        }

        trigger_error(sprintf('Undefined property: %s::$%s', __CLASS__, $name), E_USER_NOTICE);
    }

    /**
     * 
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', array($name, $value));

            $this->$name = $value;

            return;
        }

        $this->$name = $value;
    }

    /**
     * 
     * @param  string $name
     * @return boolean
     */
    public function __isset($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__isset', array($name));

            return isset($this->$name);
        }

        return false;
    }

    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'nome_vendedor', 'nome', 'cpfcnpj', 'endereco', 'cidade', 'data_cadastro', 'data_para_entrega', 'nota_fiscal', 'tipo_nf', 'pagamento', 'forma_pagamento', 'descricao_outra_forma_pagamento', 'telefone', 'contato', 'urgente', 'envio', 'endereco_entrega', 'obs', 'local_entrega', 'ja_aberto', 'carga', 'produtos', 'situacoes', 'situacao');
        }

        return array('__isInitialized__', 'id');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Venda $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

            unset($this->nome_vendedor, $this->nome, $this->cpfcnpj, $this->endereco, $this->cidade, $this->data_cadastro, $this->data_para_entrega, $this->nota_fiscal, $this->tipo_nf, $this->pagamento, $this->forma_pagamento, $this->descricao_outra_forma_pagamento, $this->telefone, $this->contato, $this->urgente, $this->envio, $this->endereco_entrega, $this->obs, $this->local_entrega, $this->ja_aberto, $this->carga, $this->produtos, $this->situacoes, $this->situacao);
        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getSituacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSituacao', array());

        return parent::getSituacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setSituacao($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSituacao', array($val));

        return parent::setSituacao($val);
    }

    /**
     * {@inheritDoc}
     */
    public function getCarga()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCarga', array());

        return parent::getCarga();
    }

    /**
     * {@inheritDoc}
     */
    public function setCarga($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCarga', array($val));

        return parent::setCarga($val);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnvio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnvio', array());

        return parent::getEnvio();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnvio($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnvio', array($val));

        return parent::setEnvio($val);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnderecoEntrega()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnderecoEntrega', array());

        return parent::getEnderecoEntrega();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnderecoEntrega($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnderecoEntrega', array($val));

        return parent::setEnderecoEntrega($val);
    }

    /**
     * {@inheritDoc}
     */
    public function getObs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObs', array());

        return parent::getObs();
    }

    /**
     * {@inheritDoc}
     */
    public function setObs($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObs', array($val));

        return parent::setObs($val);
    }

    /**
     * {@inheritDoc}
     */
    public function getContato()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContato', array());

        return parent::getContato();
    }

    /**
     * {@inheritDoc}
     */
    public function setContato($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContato', array($val));

        return parent::setContato($val);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalEntrega()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalEntrega', array());

        return parent::getLocalEntrega();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalEntrega($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalEntrega', array($val));

        return parent::setLocalEntrega($val);
    }

    /**
     * {@inheritDoc}
     */
    public function getAberto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAberto', array());

        return parent::getAberto();
    }

    /**
     * {@inheritDoc}
     */
    public function setAberto($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAberto', array($val));

        return parent::setAberto($val);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getNome_vendedor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome_vendedor', array());

        return parent::getNome_vendedor();
    }

    /**
     * {@inheritDoc}
     */
    public function setNome_vendedor($nome_vendedor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome_vendedor', array($nome_vendedor));

        return parent::setNome_vendedor($nome_vendedor);
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', array());

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', array($nome));

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function getCpfcnpj()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCpfcnpj', array());

        return parent::getCpfcnpj();
    }

    /**
     * {@inheritDoc}
     */
    public function setCpfcnpj($cpfcnpj)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCpfcnpj', array($cpfcnpj));

        return parent::setCpfcnpj($cpfcnpj);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndereco()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndereco', array());

        return parent::getEndereco();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndereco($endereco)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndereco', array($endereco));

        return parent::setEndereco($endereco);
    }

    /**
     * {@inheritDoc}
     */
    public function getCidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCidade', array());

        return parent::getCidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setCidade($cidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCidade', array($cidade));

        return parent::setCidade($cidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getData_cadastro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_cadastro', array());

        return parent::getData_cadastro();
    }

    /**
     * {@inheritDoc}
     */
    public function setData_cadastro($data_cadastro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData_cadastro', array($data_cadastro));

        return parent::setData_cadastro($data_cadastro);
    }

    /**
     * {@inheritDoc}
     */
    public function getData_entrega()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_entrega', array());

        return parent::getData_entrega();
    }

    /**
     * {@inheritDoc}
     */
    public function setData_entrega($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData_entrega', array($data));

        return parent::setData_entrega($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getNota_fiscal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNota_fiscal', array());

        return parent::getNota_fiscal();
    }

    /**
     * {@inheritDoc}
     */
    public function setNota_fiscal($nota_fiscal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNota_fiscal', array($nota_fiscal));

        return parent::setNota_fiscal($nota_fiscal);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo_nf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo_nf', array());

        return parent::getTipo_nf();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo_nf($tipo_nf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo_nf', array($tipo_nf));

        return parent::setTipo_nf($tipo_nf);
    }

    /**
     * {@inheritDoc}
     */
    public function getPagamento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPagamento', array());

        return parent::getPagamento();
    }

    /**
     * {@inheritDoc}
     */
    public function setPagamento($pagamento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPagamento', array($pagamento));

        return parent::setPagamento($pagamento);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefone', array());

        return parent::getTelefone();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefone($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefone', array($val));

        return parent::setTelefone($val);
    }

    /**
     * {@inheritDoc}
     */
    public function getForma_pagamento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getForma_pagamento', array());

        return parent::getForma_pagamento();
    }

    /**
     * {@inheritDoc}
     */
    public function setForma_pagamento($forma_pagamento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setForma_pagamento', array($forma_pagamento));

        return parent::setForma_pagamento($forma_pagamento);
    }

    /**
     * {@inheritDoc}
     */
    public function getOutra()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOutra', array());

        return parent::getOutra();
    }

    /**
     * {@inheritDoc}
     */
    public function setOutra($outra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOutra', array($outra));

        return parent::setOutra($outra);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrgente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrgente', array());

        return parent::getUrgente();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrgente($urgente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrgente', array($urgente));

        return parent::setUrgente($urgente);
    }

}
