<h3 class="page-header">Cadastro de Vendas <span class="label label-primary" style="font-size: 14px; vertical-align: middle; margin-left: 10px;">BLOCOS DE CONCRETO</span></h3>

<div class="alert alert-info">
  <span>Ao salvar, será feito o downlaod de um PDF com os ítens gravados.</span>
</div>
<div id="msg">
</div>

<form method="post">
  <div class="row">

    <div class="form-group col-md-3 col-sm-12 has-feedback">
      <label for="data">Nome do Vendedor</label>
      <input type="text" class="form-control" value="<?php echo ($this->venda != null) ? $this->venda->getNome_vendedor() : ''; ?>" required name="vendedor">
    </div>
  </div>
  <hr />
  <div class="row">

    <div class="form-group col-md-2 col-sm-12 has-feedback">
      <label for="data">Nome</label>
      <input type="text" class="form-control" required name="nome" value="<?php echo ($this->venda != null) ? $this->venda->getNome() : ''; ?>">
    </div>

    <div class="form-group col-md-2 col-sm-12 has-feedback">

      <label for="data" class="radio-inline">
        <input type="radio" name="documento" value="cpf" checked><b> CPF ou</b>
      </label>
      <label for="data" class="radio-inline">
        <input type="radio" name="documento" value="cnpj"><b> CNPJ</b>
      </label>
      <input type="text" class="form-control" required id="cpfcnpj" style="margin-top: 4px;" name="cpfcnpj" value="<?php echo ($this->venda != null) ? $this->venda->getCpfcnpj() : ''; ?>">
    </div>

    <div class="form-group col-md-2 col-sm-12 has-feedback">
      <label for="data">Endereço</label>
      <input type="text" class="form-control" required name="endereco" value="<?php echo ($this->venda != null) ? $this->venda->getEndereco() : ''; ?>">
    </div>

    <div class="form-group col-md-2 col-sm-12 has-feedback">
      <label for="data">Telefone do Cliente</label>
      <input type="text" class="form-control" id="telefone" required name="telefone" value="<?php echo ($this->venda != null) ? $this->venda->getTelefone() : ''; ?>">
    </div>

    <div class="form-group col-md-2 col-sm-12 has-feedback">
      <label for="data">Contato na Empresa</label>
      <input type="text" class="form-control" name="contato" value="<?php echo ($this->venda != null) ? $this->venda->getContato() : ''; ?>">
    </div>

    <div class="form-group col-md-2 col-sm-12 has-feedback">
      <label for="data">Cidade</label>
      <select name="cidade" required id="cidade" class="form-control">
        <option value="">- Selecione -</option>
        <?php foreach ($this->cidades as $c) { ?>
          <option value="<?php echo $c->getNome(); ?>" <?php echo ($this->venda != null && $this->venda->getCidade() == $c->getNome()) ? ' selected' : ''; ?>><?php echo $c->getNome() ?></option>
        <?php } ?>
      </select>
    </div>

  </div>

  <div class="row">

    <div class="form-group col-md-2 col-sm-12 has-feedback">
      <label for="data">Data Entrega</label>
      <input type="text" class="form-control calendario" required name="data_entrega" value="<?php echo ($this->venda != null) ? $this->venda->getData_entrega() : ''; ?>">
      <i class="glyphicon glyphicon-calendar form-control-feedback"></i>
    </div>

    <div class="form-group col-md-2 col-sm-12">
      <label for="nota_fiscal">Nota Fiscal</label>
      <div class="form-group">
        <label class="radio-inline">
          <input type="radio" required name="nota_fiscal" value="Sim" <?php echo ($this->venda != null && $this->venda->getNota_fiscal()) ? ' checked' : ''; ?>> Sim
        </label>
        <label class="radio-inline">
          <input type="radio" name="nota_fiscal" value="Não" <?php echo ($this->venda != null && !$this->venda->getNota_fiscal()) || $this->venda == null ? ' checked' : ''; ?>> Não
        </label>
      </div>
    </div>
    <div class="form-group col-md-2 col-sm-12">
      <label for="nota_fiscal">Tipo Nota Fiscal</label>
      <div class="form-group">
        <label class="radio-inline">
          <input type="radio" required name="tipo_nota_fiscal" value="No" <?php echo ($this->venda != null && $this->venda->getTipo_nf() == 'No') ? ' checked' : ''; ?>> Normal
        </label>
        <label class="radio-inline">
          <input type="radio" name="tipo_nota_fiscal" value="Ba" <?php echo (($this->venda != null && $this->venda->getTipo_nf() != 'No') || $this->venda == null) ? ' checked' : ''; ?>> Baixa
        </label>
      </div>
    </div>

    <div class="form-group col-md-2 col-sm-12 has-feedback">
      <label for="pagamento">Pagamento</label>
      <div class="form-group">
        <label class="radio-inline">
          <input type="radio" required name="pagamento" value="EN" <?php echo ($this->venda != null && $this->venda->getPagamento() == 'EN') ? ' checked' : ''; ?>> Na Entrega
        </label>
        <label class="radio-inline">
          <input type="radio" name="pagamento" value="AN" <?php echo ($this->venda != null && $this->venda->getPagamento() == 'AN') ? ' checked' : ''; ?>> Antecipado
        </label>
      </div>
    </div>

    <div class="form-group col-md-2 col-sm-12 has-feedback">
      <label for="forma_pagamento">Forma de Pagamento</label>
      <select class="form-control" id="forma_pagamento" required name="forma_pagamento">
        <option value="">- Selecione -</option>
        <option value="AV" <?php echo ($this->venda != null && $this->venda->getForma_pagamento() == 'AV') ? ' selected' : ''; ?>>À Vista</option>
        <option value="CH" <?php echo ($this->venda != null && $this->venda->getForma_pagamento() == 'CH') ? ' selected' : ''; ?>>Cheque</option>
        <option value="TR" <?php echo ($this->venda != null && $this->venda->getForma_pagamento() == 'TR') ? ' selected' : ''; ?>>Transferência</option>
        <option value="OU" <?php echo ($this->venda != null && $this->venda->getForma_pagamento() == 'OU') ? ' selected' : ''; ?>>Outros</option>
      </select>
    </div>

    <div id="obs" class="form-group col-md-2 col-sm-12 has-feedback">
      <label for="observacao">Forma de pagamento</label>
      <input type="text" class="form-control" id="observacao" name="observacao" value="<?php echo ($this->venda != null) ? $this->venda->getOutra() : ''; ?>">
    </div>

    <div class="form-group col-md-2 col-sm-12">
      <label for="urgente">Urgente</label>
      <div class="form-group">
        <label class="radio-inline">
          <input type="radio" required name="urgente" value="Sim" <?php echo ($this->venda != null && $this->venda->getUrgente() == 'Sim') ? ' checked' : ''; ?>> Sim
        </label>
        <label class="radio-inline">
          <input type="radio" required name="urgente" value="Não" <?php echo ($this->venda != null && $this->venda->getUrgente() != 'Sim') || $this->venda == null ? ' checked' : ''; ?>> Não
        </label>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-2 col-sm-12">
      <label for="urgente">Entregar / Retirar</label>
      <div class="form-group">
        <label class="radio-inline">
          <input type="radio" required name="envio" value="Entregar" <?php echo ($this->venda != null && ($this->venda->getEnvio() || $this->venda->getEnvio() == null)) ? ' checked' : ''; ?>> Entregar
        </label>
        <label class="radio-inline">
          <input type="radio" name="envio" value="Retirar" <?php echo ($this->venda != null && $this->venda->getEnvio() === false) ? ' checked' : ''; ?>> Retirar
        </label>
      </div>
    </div>

    <div class="form-group col-md-2 col-sm-12">
      <label for="urgente">Entregar no mesmo endereço</label>
      <div class="form-group">
        <label class="radio-inline">
          <input type="radio" required name="outroendereco" value="Sim" <?php echo ($this->venda != null && $this->venda->getLocalEntrega() || $this->venda->getLocalEntrega() == null) ? ' checked' : ''; ?>> Sim
        </label>
        <label class="radio-inline">
          <input type="radio" name="outroendereco" value="Não" <?php echo ($this->venda != null && $this->venda->getLocalEntrega() === false) ? ' checked' : ''; ?>> Não
        </label>
      </div>
    </div>

    <div id="endereco_entrega" class="form-group col-md-2 col-sm-12 has-feedback">
      <label for="data">Endereço Entrega</label>
      <input type="text" class="form-control" name="endereco_entrega" value="<?php echo ($this->venda != null) ? $this->venda->getEnderecoEntrega() : ''; ?>">
    </div>
  </div>

  <div class="row">

    <div class="form-group col-md-6 col-sm-12">
      <label for="observacao">Observação</label>
      <textarea class="form-control" id="obs" name="obs"><?php echo ($this->venda != null) ? $this->venda->getObs() : ''; ?></textarea>
    </div>

  </div>


  <div id="produtos">
    <?php
    $qtd_prod = 0;

    if ($this->produtos != null) {

      $key = 0;
      foreach ($this->produtos as $p) {
        $key++;
    ?>

        <input type="hidden" value="<?php echo $p->getId(); ?>" class="hdd" name="id_produto_[]">
        <div class="row item-pedido" id="a_<?php echo $p->getId(); ?>" data-id="<?php echo $p->getId(); ?>">

          <hr>

          <div class="form-group col-md-3">
            <label for="modelo_<?php echo $p->getId(); ?>">Produto</label>
            <select class="form-control" name="modelo_<?php echo $p->getId(); ?>">
              <option value="" <?php ($p->getModelo() == '') ? 'Selected' : ''; ?>>- Selecione -</option>
              <option value="Bloco A" <?php if ($p->getModelo() == 'Bloco A') echo 'selected'; ?>>Bloco A</option>
              <option value="Bloco B" <?php if ($p->getModelo() == 'Bloco B') echo 'selected'; ?>>Bloco B</option>
              <option value="Bloco C" <?php if ($p->getModelo() == 'Bloco C') echo 'selected'; ?>>Bloco C</option>
              <option value="1/2 Bloco" <?php if ($p->getModelo() == '1/2 Bloco') echo 'selected'; ?>>1/2 Bloco</option>
              <option value="Canaleta" <?php if ($p->getModelo() == 'Canaleta') echo 'selected'; ?>>Canaleta</option>
              <option value="Compensador" <?php if ($p->getModelo() == 'Compensador') echo 'selected'; ?>>Compensador</option>
              <option value="Pirulito" <?php if ($p->getModelo() == 'Pirulito') echo 'selected'; ?>>Pirulito</option>
              <option value="Paver" <?php if ($p->getModelo() == 'Paver') echo 'selected'; ?>>Paver</option>
              <option value="Frete" <?php if ($p->getModelo() == 'Frete') echo 'selected'; ?>>Frete</option>
            </select>
          </div>

          <div class="form-group col-md-2">
            <label for="cor_<?php echo $p->getId(); ?>">Medida</label>
            <select class="form-control" name="cor_<?php echo $p->getId(); ?>">
              <option value="" <?php echo ($p->getMedida() == '') ? 'Selected' : ''; ?>>- Selecione -</option>
              <option value="09x19x19" <?php echo ($p->getMedida() == '09x19x19') ? 'Selected' : ''; ?>>09x19x19</option>
              <option value="09x19x39" <?php echo ($p->getMedida() == '09x19x39') ? 'Selected' : ''; ?>>09x19x39</option>
              <option value="11,5x19x04" <?php echo ($p->getMedida() == '11,5x19x04') ? 'Selected' : ''; ?>>11,5x19x04</option>
              <option value="11,5x19x11,5" <?php echo ($p->getMedida() == '11,5x19x11,5') ? 'Selected' : ''; ?>>11,5x19x11,5</option>
              <option value="11,5x19x19" <?php echo ($p->getMedida() == '11,5x19x19') ? 'Selected' : ''; ?>>11,5x19x19</option>
              <option value="11,5x19x24" <?php echo ($p->getMedida() == '11,5x19x24') ? 'Selected' : ''; ?>>11,5x19x24</option>
              <option value="11,5x19x36,5" <?php echo ($p->getMedida() == '11,5x19x36,5') ? 'Selected' : ''; ?>>11,5x19x36,5</option>
              <option value="11,5x19x39" style="font-weight: bold;" <?php echo ($p->getMedida() == '11,5x19x39') ? 'Selected' : ''; ?>>11,5x19x39</option>
              <option value="14x19x19" <?php echo ($p->getMedida() == '14x19x19') ? 'Selected' : ''; ?>>14x19x19</option>
              <option value="14x19x34" <?php echo ($p->getMedida() == '14x19x34') ? 'Selected' : ''; ?>>14x19x34</option>
              <option value="14x19x39" style="font-weight: bold;" <?php echo ($p->getMedida() == '14x19x39') ? 'Selected' : ''; ?>>14x19x39</option>
              <option value="14x19x54" <?php echo ($p->getMedida() == '14x19x54') ? 'Selected' : ''; ?>>14x19x54</option>
              <option value="19x19x19" <?php echo ($p->getMedida() == '19x19x19') ? 'Selected' : ''; ?>>19x19x19</option>
              <option value="19x19x39" <?php echo ($p->getMedida() == '19x19x39') ? 'Selected' : ''; ?>>19x19x39</option>
              <option value="Retangular 6" <?php echo ($p->getMedida() == 'Retangular 6') ? 'Selected' : ''; ?>>Retangular 6</option>
              <option value="Retangular 8" <?php echo ($p->getMedida() == 'Retangular 8') ? 'Selected' : ''; ?>>Retangular 8</option>
              <option value="16 Faces 6" <?php echo ($p->getMedida() == '16 Faces 6') ? 'Selected' : ''; ?>>16 Faces 6</option>
              <option value="16 Faces 8" <?php echo ($p->getMedida() == '16 Faces 8') ? 'Selected' : ''; ?>>16 Faces 8</option>
            </select>
          </div>

          <div class="form-group col-md-2">
            <label for="quantidade_<?php echo $p->getId(); ?>">Quantidade</label>
            <input type="number" placeholder="Informe a Quantidade" value="<?php echo $p->getQuantidade() ?>" class="form-control quantidade" name="quantidade_<?php echo $p->getId(); ?>" id="quantidade_<?php echo $p->getId(); ?>">
          </div>

          <div class="form-group col-md-2">
            <label for="valor_<?php echo $p->getId(); ?>">Valor</label>
            <input type="text" placeholder="Informe o Valor unitário" data-thousands="." data-decimal="," value="<?php echo $p->getValor() ?>" class="form-control valor" name="valor_<?php echo $p->getId(); ?>" id="valor_<?php echo $p->getId(); ?>">
          </div>

          <div class="form-group col-md-2">
            <label for="valortotal_<?php echo $p->getId(); ?>">Total</label>
            <input type="text" disabled placeholder="Valor total" data-thousands="." required="" data-decimal="," class="form-control valor" name="total_<?php echo $p->getId(); ?>" id="total_<?php echo $p->getId(); ?>">
          </div>

          <div class="form-group col-md-1">
            <i class="glyphicon glyphicon-trash red icone" onclick="removerItem('a_<?php echo $p->getId(); ?>')"></i>
          </div>

        </div>
    <?php
      }
      $qtd_prod = $key;
    }
    ?>

  </div>

  <hr />


  <div class="row">
    <div class="col-md-12 col-sm-12">
      <p class='pull-right'>Total Geral: R$ <input type="text" disabled="" data-thousands="." required="" data-decimal="," class="form-control" id="total"></p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 col-sm-12">

      <span class="btn btn-success" id="add-produto">Add Produto</span>

      <button type="submit" class="btn btn-primary pull-right">Salvar</button>
      <button type="button" onclick="window.history.back();" class="btn btn-default pull-right">Cancelar</button>
    </div>
  </div>

  <input type="hidden" id="qtd_produtos" name="qtd_produtos" value="<?= $qtd_prod ?>">
</form>


<link href="/css/select2.min.css" rel="stylesheet" />
<script src="/js/select2.min.js"></script>
<script>
  $(document).ready(function() {

    $("#cpfcnpj").mask("999.999.999-99");

    $('#cidade').select2();

    <?php echo ($this->venda != null && $this->venda->getForma_pagamento() == 'OU') ? ' $(\'#obs\').show();' : '$(\'#obs\').hide();'; ?>

    $('#forma_pagamento').change(function() {
      if ($(this).val() == "OU") {
        $('#obs').show();
      } else {
        $('#obs').hide();
      }
    });

    $("#telefone").mask("(99) 99999-9999");
    <?php if ($this->venda == null || ($this->venda != null && $this->venda->getLocalEntrega() || $this->venda->getLocalEntrega() == null)) {
      echo "$('#endereco_entrega').hide();";
    }
    ?>


    $('input[type=radio][name=outroendereco]').change(function() {
      if (this.value == "Não") {
        $('#endereco_entrega').show();
      } else {
        $('#endereco_entrega').hide();
      }
    });

    $('body').on('focus', ".calendario", function() {
      $(this).datepicker({
        dateFormat: 'dd/mm/yy',
        dayNames: ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'],
        dayNamesMin: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S', 'D'],
        dayNamesShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb', 'Dom'],
        monthNames: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
        monthNamesShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
        nextText: 'Próximo',
        prevText: 'Anterior'
      });
    });

    $('#add-produto').click(function() {
      var qtd_produtos = $('#qtd_produtos').val();
      qtd_produtos++;

      $('#qtd_produtos').val(qtd_produtos);
      var produtos = $('#produtos');

      var row = $('<div>').addClass('row item-pedido').attr({
        id: 'a_' + qtd_produtos,
        'data-id': qtd_produtos
      });

      row.append('<hr />');

      var inputHidden = $('<input type="hidden">').addClass('hdd').attr({
        name: 'id_produto_[]'
      }).attr({
        value: qtd_produtos
      })

      row.append(inputHidden);


      //PRODUTO (MODELO)
      var modelo = $('<div>').addClass('form-group col-md-3');
      var labelModelo = $('<label>').attr({
        for: 'modelo_' + qtd_produtos
      }).text('Produto');
      var selectModelo = $('<select>').addClass('form-control').attr({
          name: 'modelo_' + qtd_produtos,
          id: 'cientes_id',
          required: true
        })
        .append('<option value="">- Selecione -</option>')
        .append('<option value="Bloco A">Bloco A</option>')
        .append('<option value="Bloco B">Bloco B</option>')
        .append('<option value="Bloco C">Bloco C</option>')
        .append('<option value="1/2 Bloco">1/2 Bloco</option>')
        .append('<option value="Canaleta">Canaleta</option>')
        .append('<option value="Compensador">Compensador</option>')
        .append('<option value="Pirulito">Pirulito</option>')
        .append('<option value="Paver">Paver</option>')
        .append('<option value="Frete">Frete</option>');

      modelo.append(labelModelo);
      modelo.append(selectModelo);
      row.append(modelo);

      //MEDIDA
      var cor = $('<div>').addClass('form-group col-md-2');
      var labelCor = $('<label>').attr({
        for: 'cor_' + qtd_produtos
      }).text('Medida');
      var selectCor = $('<select>').addClass('form-control').attr({
          name: 'cor_' + qtd_produtos,
          required: true
        })
        .append('<option value="" >- Selecione -</option>')
        .append('<option value="09x19x19">09x19x19</option>')
        .append('<option value="09x19x39">09x19x39</option>')
        .append('<option value="11,5x19x04">11,5x19x04</option>')
        .append('<option value="11,5x19x11,5">11,5x19x11,5</option>')
        .append('<option value="11,5x19x19">11,5x19x19</option>')
        .append('<option value="11,5x19x24">11,5x19x24</option>')
        .append('<option value="11,5x19x36,5">11,5x19x36,5</option>')
        .append('<option value="11,5x19x39" style="font-weight: bold;">11,5x19x39</option>')
        .append('<option value="14x19x19">14x19x19</option>')
        .append('<option value="14x19x34">14x19x34</option>')
        .append('<option value="14x19x39" style="font-weight: bold;">14x19x39</option>')
        .append('<option value="14x19x54">14x19x54</option>')
        .append('<option value="19x19x19">19x19x19</option>')
        .append('<option value="19x19x39">19x19x39</option>')
        .append('<option value="Retangular 6">Retangular 6</option>')
        .append('<option value="Retangular 8">Retangular 8</option>')
        .append('<option value="16 Faces 6">16 Faces 6</option>')
        .append('<option value="16 Faces 8">16 Faces 8</option>');

      cor.append(labelCor);
      cor.append(selectCor);
      row.append(cor);

      //QUANTIDADE  
      var quantidade = $('<div>').addClass('form-group col-md-2');
      var labelQuantidade = $('<label>').attr({
        for: 'quantidade_' + qtd_produtos
      }).text('Quantidade');
      var inputQuantidade = $('<input type="number" placeholder="Informe a Quantidade" required>').addClass('form-control quantidade').attr({
        name: 'quantidade_' + qtd_produtos
      }).attr({
        id: 'quantidade_' + qtd_produtos
      })

      quantidade.append(labelQuantidade);
      quantidade.append(inputQuantidade);
      row.append(quantidade);


      //VALOR
      var valor = $('<div>').addClass('form-group col-md-2');
      var labelvalor = $('<label>').attr({
        for: 'valor_' + qtd_produtos
      }).text('Valor');
      var inputvalor = $('<input type="text" placeholder="Informe o Valor unitário" data-thousands="." required data-decimal=",">').addClass('form-control valor').attr({
        name: 'valor_' + qtd_produtos
      }).attr({
        id: 'valor_' + qtd_produtos
      })

      valor.append(labelvalor);
      valor.append(inputvalor);
      row.append(valor);

      //TOTAL
      var total = $('<div>').addClass('form-group col-md-2');
      var labeltotal = $('<label>').attr({
        for: 'valortotal_' + qtd_produtos
      }).text('Total');
      var inputtotal = $('<input type="text" disabled placeholder="Valor total" data-thousands="." required data-decimal=",">').addClass('form-control valor').attr({
        name: 'total_' + qtd_produtos
      }).attr({
        id: 'total_' + qtd_produtos
      })

      total.append(labeltotal);
      total.append(inputtotal);
      row.append(total);

      //Lixeira
      var lixeira = $('<div>').addClass('form-group col-md-1');
      var ivalor = $('<i onclick="removerItem(\'a_' + qtd_produtos + '\')">').addClass('glyphicon glyphicon-trash red icone');

      lixeira.append(ivalor);
      row.append(lixeira);

      produtos.append(row);

      $(".valor").maskMoney();

      $(".valor").focusout(function() {
        Totalizar()
      });
      $(".quantidade").focusout(function() {
        Totalizar()
      });

    });

    $(".valor").maskMoney();

    $(".valor").focusout(function() {
      Totalizar()
    });
    $(".quantidade").focusout(function() {
      Totalizar()
    });

    $("input[name ='documento']").click(function() {
      try {
        $("#cpfcnpj").unmask();
      } catch (e) {}
      //alert($(this).val());
      if ($(this).val() == 'cpf') {
        $("#cpfcnpj").mask("999.999.999-99");
      } else {
        $("#cpfcnpj").mask("99.999.999/9999-99");
      }

      // ajustando foco
      var elem = this;
      setTimeout(function() {
        // mudo a posição do seletor
        elem.selectionStart = elem.selectionEnd = 10000;
      }, 0);
      // reaplico o valor para mudar o foco
      var currentValue = $(this).val();
      $(this).val('');
      $(this).val(currentValue);
    });

    Totalizar();
  });

  function removerItem(id) {
    if (confirm("Deseja realmente remover este item?")) {
      $('#' + id).remove();
      $("#msg").addClass("alert alert-success").text("Produto removido com sucesso!");
      var qtd = $('#qtd_produtos').val();
      $('#qtd_produtos').val(qtd - 1);
      Totalizar();
    }
  }

  function Totalizar() {
    var totalG = 0;
    $(".item-pedido").each(function(index) {
      var i = $(this).attr('data-id');
      var valor = parseFloat($("#valor_" + i).val() != '' ? $("#valor_" + i).val().replace('.', '').replace(',', '.') : 0);
      var quantidade = parseInt($('#quantidade_' + i).val() != '' ? $('#quantidade_' + i).val() : 0);
      var total = (valor * quantidade);
      total = parseFloat(total.toFixed(2));

      $('#total_' + i).val(total);
      $('#total_' + i).maskMoney();
      $('#total_' + i).trigger('mask.maskMoney');
      totalG += total;
    });

    $('#total').val(parseFloat(totalG.toFixed(2)));
    $('#total').maskMoney();
    $('#total').trigger('mask.maskMoney');
  }
</script>