<?php
            if(isset($this->result) && count($this->result) > 0){?>
                <div class="alert alert-<?php echo $this->result["tipo_mens"];?>">
    	            <?php echo $this->result["resp"];?> 
                </div>
            <?php 
            }?>

<div id="top" class="row no_print">

	<div class="col-sm-3">
		<h2>Cidades</h2>
	</div>

</div>

<hr />


<form method="post" >
    
	    <div class="row">
		    <div class="form-group col-md-2 col-sm-12 has-feedback">
        		<label for="cliente_nome">Nome da Cidade</label> 
        	    <input type="text" class="form-control" id="cliente_nome" name="cliente_nome" placeholder="Informe o nome da cidade">
		    </div>
        </div>

        <div class="form-group col-md-2">
		    <button type="submit" class="btn btn-primary">Salvar</button>
		 </div>

	    </div>

</form>

<!-- /#list -->

<hr />

<div id="top" class="row">
	<div class="col-sm-3">
		<h2>Lista de Cidades</h2>
	</div>
</div>

<!-- /#top -->

<hr />

<div id="list" class="row">
	<div class="table-responsive col-md-12">
		<table class="table table-striped" cellspacing="0" cellpadding="0" id="lista_vendas">
			<thead>
				<tr>
					<th>ID</th>
					<th>Nome</th>
					<th class="actions">Ações</th>
				</tr>
			</thead>

			<tbody>
				<?php foreach ($this->lista as $f): ?>
					<tr>
						<td><?php echo $f->getId(); ?></td>
						<td><?php echo $f->getNome(); ?></td>
						<td class="actions">
							<a class="btn btn-danger btn-xs" href="#" id="excluircliente" onclick="enviarIdcliente(<?php echo $f->getId();?>)">Excluir</a>
						</td>
					</tr>
                <?php endforeach; ?>

			</tbody>
		</table>

	</div>
</div>


<script type="text/javascript">
    $(document).ready( function () {
	    
		$('#lista_vendas').DataTable({
    		"language": {
                "url": "https://cdn.datatables.net/plug-ins/1.10.12/i18n/Portuguese-Brasil.json"
    		},
			"order": [[1, "asc"]],
		});


    });

	
	function enviarIdcliente(id){

		if(confirm("Deseja realmente excluir esta cidade?"))
		{
			window.location.href = "<?php echo $this->url('excluircidade'); ?>"+id;
		}

	}
</script>