<?php
if(isset($this->result) && count($this->result) > 0){?>
    <div class="alert alert-<?php echo $this->result["tipo_mens"];?>">
        <?php echo $this->result["resp"];?> 
    </div>
<?php 
}?>
<style type="text/css" media="print">

     body{
        font-size: 8px;
        max-height:100%; 
        max-width:100%;
        margin-top: 1.2cm;
        margin-bottom: 1.2cm;
        margin-left: 1cm;
        margin-right: 1cm;
        size: landscape;
     } 

     table{
        border: 1px !important;
     }

    .yesprint {
      	visibility: visible;
      	position: absolute;
		top: 0;
		left: 0;
		border: 1px;
    }

    .yesprint2 {
      	visibility: visible;
		position: absolute;
		bottom: 0;
		right: 0;
		border: 1px;
    }

    .tab_prod{
        visibility: visible;
        border: 1px !important;
    }

    .no_print{
        visibility: hidden;
    }

    .label{
        display: inline-block;
        min-width: 10px;
        padding: 3px 7px;
        font-size: 12px;
        font-weight: 700;
        line-height: 1;
        color: #fff;
        text-align: center;
        white-space: nowrap;
        vertical-align: middle;
        background-color: #777;
        border-radius: 10px;
    }

    .check{
        width: 100% !important;
        height: 48px !important;
    }

</style>

<div id="top" class="row no_print">

	<div class="col-sm-12
    <?php 
    switch ($this->filtro['situacao']) {
	    case 'Recebido':
		    echo 'linha';
		    break;
	    case 'Carregamento':
		    echo 'linha_carga';
		    break;
	    case 'Entrega':
		    echo 'linha_entrega';
		    break;
	    case 'Finalizados':
		    echo 'linha_finalizado';
		    break;
	    case 'Excluidos':
		    echo 'linha_excluidos';
		    break;
    }
    ?>
    ">
		<h2>Listar Vendas - <?php echo $this->filtro['situacao'] == 'Recebido' ? 'Pedidos Novos' : $this->filtro['situacao'] ?></h2>
	</div>

</div>

<hr class="no_print" />

<form method="post" class="no_print" id="filtros">

    <fieldset>
        <legend>Filtros</legend>

	    <div class="row">

		    <div class="form-group col-md-2 col-sm-12 has-feedback">
			    <label for="cliente">Cliente</label>
			    <input type="text" class="form-control" name="nome" value="<?php if(isset($this->filtro['nome']))echo $this->filtro['nome'];?>"> 
		    </div>
        
            <div class="form-group col-md-2 col-sm-12 has-feedback">
			    <label for="cliente">CPF / CNPJ</label>
			    <input type="text" class="form-control" id="cpfcnpj" name="cpfcnpj" value="<?php if(isset($this->filtro['cpfcnpj']))echo $this->filtro['cpfcnpj'];?>"> 
		    </div>
            
            <div class="form-group col-md-2 col-sm-12 has-feedback">
			    <label for="cliente">Cidade</label>
                <select name="cidade" id="cidade" class="form-control">
				    <option value="" <?php if(!isset($this->filtro['cidade']))echo "selected";?>>- Selecione -</option>
				    <?php foreach ($this->cidades as $c){ ?>
					    <option value="<?php echo $c->getNome();?>" <?php if(isset($this->filtro['cidade']) && $this->filtro['cidade'] == $c->getNome())echo "selected";?>><?php echo $c->getNome()?></option>
				    <?php }?>
			    </select>
		    </div>
        
		    <div class="form-group col-md-2 col-sm-12 has-feedback">
			    <label for="data">Data Entrega</label> 
			    <input type="text" class="form-control calendario" name="data_entrega" value="<?php if(isset($this->filtro['data_entrega']))echo $this->filtro['data_entrega'];?>"> 
			    <i class="glyphicon glyphicon-calendar form-control-feedback"></i>
		    </div>

            <div class="form-group col-md-2 col-sm-12 has-feedback">
			    <label for="cliente">Vendedor</label>
			    <input type="text" class="form-control" name="vendedor" value="<?php if(isset($this->filtro['vendedor']))echo $this->filtro['vendedor'];?>"> 
		    </div>	

            <div class="form-group col-md-2 col-sm-12 has-feedback">
                <label for="modelo">Modelo</label>
                <select class="form-control" name="modelo" id="cientes_id">
                    <option value="" <?php if(!isset($this->filtro['modelo']) || (isset($this->filtro['modelo']) && $this->filtro['modelo'] == ''))echo 'selected';?>>- Selecione -</option>
                    <option value="Super Max" <?php if(isset($this->filtro['modelo']) && $this->filtro['modelo'] == 'Super Max')echo 'selected';?>>Super Max</option>
                    <option value="Max" <?php if(isset($this->filtro['modelo']) && $this->filtro['modelo'] == 'Max')echo 'selected';?>>Max</option>
                    <option value="Coppo Venetto" <?php if(isset($this->filtro['modelo']) && $this->filtro['modelo'] == 'Coppo Venetto')echo 'selected';?>>Coppo Venetto</option>
					<option value="Super Max RESINADA" <?php if(isset($this->filtro['modelo']) && $this->filtro['modelo'] == 'Super Max RESINADA')echo 'selected';?>>Super Max RESINADA</option>
					<option value="Max RESINADA" <?php if(isset($this->filtro['modelo']) && $this->filtro['modelo'] == 'Max RESINADA')echo 'selected';?>>max RESINADA</option>
					<option value="Coppo RESINADA" <?php if(isset($this->filtro['modelo']) && $this->filtro['modelo'] == 'Coppo RESINADA')echo 'selected';?>>Coppo RESINADA</option>
                    <option value="Espigão" <?php if(isset($this->filtro['modelo']) && $this->filtro['modelo'] == 'Espigão')echo 'selected';?>>Espigão</option>
                    <option value="Inicial" <?php if(isset($this->filtro['modelo']) && $this->filtro['modelo'] == 'Inicial')echo 'selected';?>>Inicial</option>
                    <option value="03 vias" <?php if(isset($this->filtro['modelo']) && $this->filtro['modelo'] == '03 vias')echo 'selected';?>>03 vias</option>
                    <option value="04 vias" <?php if(isset($this->filtro['modelo']) && $this->filtro['modelo'] == '04 vias')echo 'selected';?>>04 vias</option>
                    <option value="Capa Lateral" <?php if(isset($this->filtro['modelo']) && $this->filtro['modelo'] == 'Capa Lateral')echo 'selected';?>>Capa Lateral</option>
                    <option value="Policarbonato Max" <?php if(isset($this->filtro['modelo']) && $this->filtro['modelo'] == 'Policarbonato Max')echo 'selected';?>>Policarbonato Max</option>
                    <option value="Policabornato Coppo" <?php if(isset($this->filtro['modelo']) && $this->filtro['modelo'] == 'Policabornato Coppo')echo 'selected';?>>Policabornato Coppo</option>
                    <option value="Policabornato Fit" <?php if(isset($this->filtro['modelo']) && $this->filtro['modelo'] == 'Policabornato Fit')echo 'selected';?>>Policabornato Fit</option>
                    <option value="Manta Termica" <?php if(isset($this->filtro['modelo']) && $this->filtro['modelo'] == 'Manta Termica')echo 'selected';?>>Manta Termica</option>
                    <option value="Frete" <?php if(isset($this->filtro['modelo']) && $this->filtro['modelo'] == 'Frete')echo 'selected';?>>Frete</option>
                </select>
            </div>
        </div>

	    <div class="row">
            <div class="form-group col-md-2 col-sm-12">
			    <div class="form-group">
				    <label class="checkbox-inline">
					    <input type="checkbox" name="envio[]" value="Entregar" <?php if(!isset($this->filtro['Entregar']) || (isset($this->filtro['Entregar']) && $this->filtro['Entregar']))echo 'checked';?>> Entregar
				    </label>
				    <label class="radio-inline">
					    <input type="checkbox" name="envio[]" value="Retirar" <?php if(!isset($this->filtro['Retirar']) || (isset($this->filtro['Entregar']) && $this->filtro['Retirar']))echo 'checked';?>> Retirar
				    </label>
			    </div>
		    </div>

            
            <div class="form-group col-md-2 col-sm-12">
			    <label for="urgente">Urgente</label> 
			    <div class="form-group">
				    <label class="checkbox-inline">
					    <input type="checkbox" name="urgente[]" value="Sim" <?php if(!isset($this->filtro['urgente']) || (isset($this->filtro['urgente']) && $this->filtro['urgente']))echo 'checked';?>> Sim
				    </label>
				    <label class="radio-inline">
					    <input type="checkbox" name="urgente[]" value="Não" <?php if(!isset($this->filtro['naoUrgente']) || (isset($this->filtro['naoUrgente']) && $this->filtro['naoUrgente']))echo 'checked';?>> Não
				    </label>
			    </div>
		    </div>

            <div class="form-group col-md-2 has-feedback">

			    <label for="limite">Exibir</label> 

			    <select name="limite" class="form-control">
				    <option value="50" <?php if(isset($this->filtro['limite']) && $this->filtro['limite'] == 50)echo 'selected';?>>50 Registros</option>
				    <option value="1000" <?php if(isset($this->filtro['limite']) && $this->filtro['limite'] == 1000)echo 'selected';?>>1000 Registros</option>
				    <option value="0" <?php if(isset($this->filtro['limite']) && $this->filtro['limite'] == 0)echo 'selected';?>>Todos Os Registros</option>
			    </select>

		    </div>

		    <div class="form-group col-md-2">
			    <button type="submit" class="btn btn-primary">Filtrar</button>
		    </div>

	    </div>
    </fieldset>
</form>

<form method="post" id="tramitar" action="<?=$this->url('tramitar'); ?>">

    <fieldset style="margin-top:10px;">
        <legend>Tramitar Situação</legend>

	    <div class="row">

            <div class="form-group col-md-2 col-sm-12 has-feedback">
                <label for="situacao">Enviar para:</label>
                <select class="form-control" name="situacao" id="situacao">
                    <option value="">- Selecione -</option>
                    <?php if($this->filtro['situacao'] != "Recebido") {echo "<option value=\"Recebido\" >Pedido Novo</option>";} ?>
                    <?php if($this->filtro['situacao'] != "Carregamento" && $this->filtro['situacao'] != "Excluidos" && $this->filtro['situacao'] != "Finalizados"  && $this->filtro['situacao'] != "Entrega" ) {echo "<option value=\"Carregamento\" >Carregamento</option>";} ?>
                    <?php if($this->filtro['situacao'] != "Entrega" && $this->filtro['situacao'] != "Excluidos" && $this->filtro['situacao'] != "Finalizados") {echo "<option value=\"Entrega\" >Entrega</option>";} ?>
                    <?php if($this->filtro['situacao'] != "Finalizados" && $this->filtro['situacao'] != "Excluidos") {echo "<option value=\"Finalizados\" >Finalizado</option>";} ?>
                    <?php if($this->filtro['situacao'] != "Excluidos") {echo "<option value=\"Excluidos\" >Excluído</option>";} ?>
                </select>
            </div>
            
		    <div class="form-group col-md-3 col-sm-12 has-feedback">
			    <label for="cliente">Cargas</label>
			    <select name="carga" id="select_carga" class="form-control" disabled>
				    <option value="">- Selecione -</option>
				    <?php 
                    foreach ($this->cargas_combo as $c){ 
                        $data_atual = date("Y/m/d");
                        if($c['data'] >= $data_atual){?>
					        <option data-situ="<?php echo $c['situacao'];?>" value="<?php echo $c['id'];?>"><?php echo $c['motorista'] ." - " . $c['data']->format('d/m/Y') . " " . $c['saida']->format('H:i') . " - " .  $c['situacao']; ?></option>
				    <?php }
                    }?>
			    </select>
		    </div>

		    <div class="form-group col-md-1">
			    <div class="icone">
				    <img alt="" src="/img/plus.png" data-toggle="modal" data-target="#carga-modal">
			    </div>
		    </div>
        
            <div class="form-group col-md-2">
			    <button id="btn_tramitar" class="btn btn-primary">Ok</button>
		    </div>     

        </div>

    </fieldset>

    <div id="list" class="row yesprint">

	    <div class="table-responsive col-md-12">
		    <table class="table table-striped table table-sm-responsive" cellspacing="0" cellpadding="0" id="lista_vendas">
                <thead>
				    <tr>
					    <th class="no_print"></th>
					    <th class="no_print"></th>
					    <th>Data Cadastro</th>
					    <th>Data Entrega</th>
					    <th>Nome</th>
                        <th>Cidade</th>
					    <th>Vendedor</th>
						<th>Cor</th>
					    <th>Super</th>
					    <th>Max</th>
					    <th>Coppo</th>
					    <th>ESP</th>
					    <th>Ini</th>
					    <th>03v</th>
					    <th>04v</th>
					    <th>Capa</th>
					    <th>Peso</th>
					    <th>Valor</th>
					    <th class="no_print"></th>
				    </tr>
			        
                </thead>
			    <tbody>

			        <?php 
                    $valorComissaoGeral = 0;
			        $valorGeral = 0;
			        $qtdTotalGeral = 0;

                    $qtdCarga = count($this->cargas);
                    if($qtdCarga == 0){
                        $qtdCarga = 1;
                    }
                    $vendasSemCarga = false;
                    for($x=0; $x<=$qtdCarga; $x++){
                        $existe = false;
                        $c = isset($this->cargas[$x])?$this->cargas[$x]:array('id' => null);
                        foreach ($this->vendas as $v){
                            if(isset($c) && $v["carga"]["id"] == $c["id"]){
                                $existe = true;
                                break;
                            }
                        }
                        if($this->filtro['situacao'] != 'Recebido' && $existe){
                            ?>
                            <tr class="<?php 
                                switch ($this->filtro['situacao']) {
	                                case 'Carregamento':
		                                echo 'linha_carga';
		                                break;
	                                case 'Entrega':
		                                echo 'linha_entrega';
		                                break;
	                                case 'Finalizados':
		                                echo 'linha_finalizado';
		                                break;
	                                case 'Excluidos':
		                                echo 'linha_excluidos';
		                                break;
                                }
                                ?>">
                            	<td>
                                    <?php if( $this->filtro['situacao'] == 'Carregamento' || $this->filtro['situacao'] == 'Entrega'){?>
                                        <input type="checkbox" class="carga_tramitar" name="carga_tramitar[]" value="<?=$c["id"]?>" />
                                    <?php } ?>
                                </td>
			      	            <td><i class="glyphicon glyphicon-plus carga no_print" id="carga_<?=$c["id"]?>"></i></td>
			      	            <td colspan="16">
                                    <b>
                                        <?php
                                            if($x==$qtdCarga){
                                                echo "Pedidos fora de carregamento";
                                            }else{
                                                echo $c['motorista'] ." - " . $c['data']->format('d/m/Y') . " " . $c['saida']->format('H:i');
                                            }   
                                         ?>
                                    </b>
                                </td>
                            </tr>
                            <tr class="tabela_carga_<?=$c["id"];?>" data-id-venda="<?=$v['id'];?>" <?php if($this->filtro['situacao'] != 'Recebido'){echo "style=\"display:none\"";} ?>>
					            <th class="no_print"></th>
					            <th class="no_print"></th>
					            <th>Data Cadastro</th>
					            <th>Data Entrega</th>
					            <th>Nome</th>
                                <th>Cidade</th>
					            <th>Vendedor</th>
								<th>Cor</th>
					            <th>Super</th>
					            <th>Max</th>
					            <th>Coppo</th>
					            <th>ESP</th>
					            <th>Ini</th>
					            <th>03v</th>
					            <th>04v</th>
					            <th>Capa</th>
					            <th>Peso</th>
					            <th>Valor</th>
					            <th class="no_print"></th>
				            </tr>
				            <?php 
                        }
                        if(($this->filtro['situacao'] == 'Recebido') && $x > 0){
                            continue;
                        }
			            foreach ($this->vendas as $v){
                            if($v["carga"] == null){
                                $v["carga"] = array('id' => null);
                            }
                            if($this->filtro['situacao'] != 'Recebido'){
                                
                                if(isset($c) && ($v["carga"]["id"] != $c["id"] ) ){
                                    continue;
                                }
                            }
                            if(! is_array($v)){
                                $v = (array)$v;
                            }
                            $id = $v['id'];
			                $valorTotalComissao = 0;?>

			                <tr class="linha tabela_carga_<?=$c["id"];?>" data-id-venda="<?=$v['id'];?>" <?php if($this->filtro['situacao'] != 'Recebido'){echo "style=\"display:none\"";} ?>>

			      	            <td>
                                    <input type="checkbox" class="item_tramitar" name="item_tramitar[]" value="<?=$id?>" />
                                    <?php if($this->filtro['situacao'] == 'Recebido' && !$v['ja_aberto']){
                                        echo "<span data-id=\"$id\" class=\"glyphicon glyphicon-asterisk asterisk\" style=\"padding-left: 10px; color: #0075ff;\"></span>";
                                    }?>
                                </td>
			      	            <td><i class="glyphicon glyphicon-plus venda no_print" id="<?= $v['id'];?>"></i></td>
			      	            <td><?= $v['data_cadastro']->format('d/m/Y');?></td>
					            <td><?= $v['data_para_entrega']->format('d/m/Y');?></td>

					            <?php 
			                    $prod = array();
                                $quantidadeTotal=0;
                                $qtdFit=0;
                                $qtdEspig=0;
                                $qtdMax=0;
                                $qtdCoppo=0;
                                $qtdIni=0;
                                $qtd03v=0;
                                $qtd04v=0;
                                $qtdCapa=0;
                                $valorTotal=0;
                                $peso = 0;
                            
                                foreach ($this->produtos as $p){

			                      if(is_object($p->getVenda()) && $p->getVenda()->id == $id){
			                          array_push($prod, $p);

			                          $quantidadeTotal += $p->getQuantidade();
			                          switch ($p->getModelo()) {
	                                    case 'Max':
										case 'Max RESINADA':   
		                                    $qtdMax += $p->getQuantidade();
                                            $peso += 5.5 * $p->getQuantidade();
		                                    break;
	                                    case 'Coppo Venetto':
										case 'Coppo Venetto RESINADA':
		                                    $qtdCoppo += $p->getQuantidade();
                                            $peso += 4.7 * $p->getQuantidade();
		                                    break;
	                                    case 'Capa Lateral':
		                                    $qtdCapa += $p->getQuantidade();
                                            $peso += 4 * $p->getQuantidade();
		                                    break;
                                        case 'Inicial':
		                                    $qtdIni += $p->getQuantidade();
                                            $peso += 3 * $p->getQuantidade();
		                                    break;
	                                    case '03 vias':
		                                    $qtd03v += $p->getQuantidade();
                                            $peso += 5 * $p->getQuantidade();
		                                    break;
	                                    case '04 vias':
		                                    $qtd04v += $p->getQuantidade();
                                            $peso += 5 * $p->getQuantidade();
		                                    break;
                                        case 'Super Max':
										case 'Super Max RESINADA':
                                            $qtdFit += $p->getQuantidade();
		                                    $peso += 3.9 * $p->getQuantidade();
		                                    break;
	                                    case 'Espigão':
                                            $qtdEspig += $p->getQuantidade();
		                                    $peso += 4 * $p->getQuantidade();
		                                    break;
	                                    case 'Policarbonato Max':
		                                    $peso += 1 * $p->getQuantidade();
		                                    break;
	                                    case 'Policarbonato Coppo':
		                                    $peso += 1 * $p->getQuantidade();
		                                    break;
	                                    case 'Policarbonato Fit':
		                                    $peso += 1 * $p->getQuantidade();
		                                    break;
	                                    case 'Manta Termica':
		                                    $peso += 1 * $p->getQuantidade();
		                                    break;
	                                    case 'Frete':
		                                    $peso += 1 * $p->getQuantidade();
		                                    break;
                                      }
	                    
			                          $valorTotal += floatval(str_replace(',', '.', $p->getValor())) * $p->getQuantidade();
			                      }
                                }
			                    $valorGeral += $valorTotal;
					            $qtdTotalGeral += $quantidadeTotal;
			                    ?>

					            <td><?php echo substr($v['nome'], 0, 30);?></td>
					            <td><?php echo substr($v['cidade'], 0, 30);?></td>
					            <td><?php echo substr($v['nome_vendedor'], 0, 10);?></td>
								<td><?php echo substr($p['cor'], 0, 10);?></td>
					            <td><?=$qtdFit ?></td>
					            <td><?=$qtdMax ?></td>
					            <td><?=$qtdCoppo ?></td>
					            <td><?=$qtdEspig ?></td>
					            <td><?=$qtdIni ?></td>
					            <td><?=$qtd03v ?></td>
					            <td><?=$qtd04v ?></td>
					            <td><?=$qtdCapa ?></td>
					            <td><?php echo number_format($peso, 0, ',', '.');?>kg</td>
					            <td>R$ <?php echo number_format($valorTotal, 2, ',', '.');?></td>
    				            <td>
                                    <?php
                                    if($v["envio"]){
                                        echo "<span title=\"Entregar\" class=\"label label-warning\"> E </span>";
                                    }else{
                                        echo "<span title=\"Retirar\" class=\"label label-success\"> R </span>";
                                    }

                                    if($v["urgente"] == 'Sim'){
                                        echo "<span title=\"Urgente\" class=\"label label-danger\"> U </span>";
                                    }
                                    $isColorido = false;
                                    foreach ($prod as $p){
                				        if($p->cor != 'Cinza Pérola'){
                                            $isColorido = true;
                                        }
                                    }
                                    if($isColorido){
                                        echo "<span title=\"Colorido\" class=\"label label-primary\"> C </span>";
                                    }
                                
                                    ?>
                                </td>

				            </tr>
				            <tr>

					            <td colspan="19" id="tabela_prod_<?=$v['id'];?>" style="display:none">

                                    <table border="1" width='100%' style='border-collapse: collapse;'>
				                        <thead>
					                        <tr>
						                        <th>Vendedor:</th>
						                        <td colspan="2"><?= $v['nome_vendedor'];?></td>
						                        <th>Data Cadastro:</th>
						                        <td><?php echo $v['data_cadastro']->format('d/m/Y');?></td>
					                        </tr>
					                        <tr>
						                        <th>Nome Cliente:</th>
						                        <td colspan="2"><?= $v['nome'];?></td>
						                        <th>Documento:</th>
						                        <td><?= $v['cpfcnpj'];?></td>
					                        </tr>
					                        <tr>
						                        <th>Telefone do Cliente:</th>
						                        <td colspan="2"><?= $v['telefone'];?></td>
                                                <th>Contato:</th>
						                        <td><?= $v['contato'];?></td>
					                        </tr>
					                        <tr>
						                        <th>Endereço:</th>
						                        <td colspan="2"><?=$v['endereco']?></td>

						                        <th>Cidade:</th>
						                        <td><?=$v['cidade']?></td>
					                        </tr>
					                        <tr>
						                        <th>Data Entrega:</th>
						                        <td colspan="2"><?php echo $v['data_para_entrega']->format('d/m/Y');?></td>
						                        <th>Urgente:</th>
						                        <td><?php echo $v['urgente'];?></td>
					                        </tr>
					                        <tr>
						                        <th>Tipo Nota Fiscal:</th>
						                        <td colspan="2"><?php echo $v['tipo_nf']=='No'? "Normal": "Baixa";?></td>

						                        <th>Nota Fiscal:</th>
						                        <td><?php echo $v['nota_fiscal']? "Sim": "Não";?></td>
					                        </tr>
					                        <tr>
						                        <th>Forma de Pagamento:</th>
						                        <td colspan="2">
                                                
                                                        <?php 
			                                            switch($v['forma_pagamento']){
				                                            case "AV":
					                                            echo "À Vista";
					                                            break;
				                                            case "CH":
					                                            echo "Cheque";
					                                            break;
				                                            case "TR":
					                                            echo "Transferência";
					                                            break;
				                                            case "OU":
					                                            echo $v['descricao_outra_forma_pagamento'];
					                                            break;
			                                            }?>
                                             
                                                </td>

						                        <th>Pagamento:</th>
						                        <td>
                                                
                                                        <?php 
			                                            switch($v['pagamento']){
				                                            case "EN":
					                                            echo "Na Entrega";
					                                            break;
				                                            case "AN":
					                                            echo "Antecipado";
					                                            break;
			                                            }?>
                                                
                                                </td>
					                        </tr>
					                        <tr>
						                        <th>Endereço Entrega:</th>
						                        <td colspan="4">
                                                
                                                        <?php 
                                                        if($v['envio']){
                                                            if($v['local_entrega']){
                                                                echo $v['endereco'];
				                                            }
                                                            else{
                                                                echo $v['endereco_entrega'];
				                                            }
                                                        }else{
                                                            echo "Retirar";
                                                        }
                                                        ?>
                                                
                                                </td>
					                        </tr>

					                        <tr>
						                        <th >Observação:</th>
						                        <td colspan="4">
                                                    <?= $v['obs']?>
                                                </td>
					                        </tr>
			                            <thead>
		                            </table>
                                  
					                <?php
                                    if(count($prod)){?>
                                        <table class="table table-striped table-sm-responsive">
							                <thead>
                                                <tr>
                                                    <th>Modelo</th>
									                <th>Cor</th>
									                <th>Quantidade</th>
									                <th>Valor</th>
									                <th>Valor Total</th>
									                <th><span class="qtd_desm_<?= $v['id'];?>" style="display:none">Quantidade a ser separado</span></th>
								                </tr>
							                </thead>
							                <tbody>
                                                <?php foreach ($prod as $p){?>
                				                    <tr>
                                                        <td><?php echo $p->getModelo(); ?></td>
                					                    <td><?php echo $p->getCor(); ?></td>
                					                    <td><?php echo $p->getQuantidade(); ?></td>
                					                    <td>R$ <?php echo $p->getValor(); ?></td>
                					                    <td>R$ <?php echo number_format(floatval(str_replace(',', '.', $p->getValor())) * $p->getQuantidade(),2, ',', '.');?></td>
                					                    <td><input type="number" class="qtd_desm_<?= $v['id'];?>" style="display:none" id="<?php echo $p->getId(); ?>" max="<?php echo $p->getQuantidade(); ?>" /></td>
								                    </tr>
                                            
                			                    <?php } ?>
                                                <tr>
                                                    <th colspan="4">Total</th>
                                                    <th>R$ <?php echo number_format(floatval($valorTotal),2, ',', '.'); ?></th>
                                                    <th></th>
								                </tr>
							                </tbody>
						        
                                        </table>
                                
	                                    <div class="row">

                                            <div class="col-md-8 col-sm-12">
			                                    <span>Obs: <b><?= $v["obs"]; ?></b></span>
		                                    </div>
                                            <div class="form-group col-md-4  col-sm-12 pull-left">
			                                    <a class="btn btn-primary" href="<?=$this->url('editar', array('id' => $v["id"])); ?>">Editar</a>
			                                    <button type="button" onclick="HabDesmembrar(<?=$v["id"];?>)" <?php if($this->filtro['situacao'] != "Recebido") {echo "style=\"display:none\"";} ?> class="btn btn-primary btn_habilitardesmembrar_<?=$v["id"];?>">Habilitar desmembramento</button>
			                                    <button type="button" onclick="desmembrar(<?=$v["id"];?>)" <?php if($this->filtro['situacao'] != "Recebido") {echo "disabled";} ?> class="btn btn-info btn_desmembrar_<?=$v["id"];?>" style="display:none">Desmembrar</button>
                                                <a class="btn btn-primary" href="<?=$this->url('imprimir', array('id' => $v["id"])); ?>" target="_blank">Declaração</a>
                                                <a class="btn btn-primary" href="<?=$this->url('recibo', array('id' => $v["id"])); ?>" target="_blank">Recibo</a>
		                                    </div>

                                        </div>
                  
                                    <?php } ?>

                                </td>
                            </tr>
			            <?php }
                    }?>

			    </tbody>
		    </table>
	    </div>
    </div>
</form>

<!-- /#list -->

<hr />

<div id="actions" class="row yesprint2">
    <div class="col-md-2 no_print">
        <a onclick="anterior();" id="anterior" class="btn btn-info"><< Anterior </a>
        <a onclick="proximo();" id="next" class="btn btn-info">Próximo >></a>
    </div>  

    <div class="col-md-4 col-sm-12">
   		<div class="pull-right">
    		<p><strong>Qtd Total</strong></p>
	 	 	<p><?php echo $qtdTotalGeral;?></p>
	  	</div>
    </div>

    <div class="col-md-3 col-sm-12">
   		<div class="pull-right">
    		<p><strong>Valor total das Vendas</strong></p>
	 	 	<p>R$ <?php echo number_format($valorGeral, 2, ',', '.');?></p>
	  	</div>
    </div>
</div>


<div class="modal fade" id="carga-modal" tabindex="-1" role="dialog" aria-labelledby="modalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
					<span aria-hidden="true">&times;</span>
				</button>
				<h4 class="modal-title" id="modalLabel">Cadastrar Nova carga</h4>
			</div>
			<div class="modal-body">
                <!--<div class="form-group">
                    <label class="radio-inline">
					    <input type="checkbox" name="situacao_carga" id="situacao_carga" value="Entrega"> Direto Para Entrega
				    </label>
    			</div>-->
                <div class="form-group">
        		    <label for="motorista">Motorista</label>
                    <select required class="form-control" name="motorista_carga" id="motorista_carga">
                        <option value="">- Selecione -</option>
                        <option value="Cesar">Cesar</option>
                        <option value="Fábio">Fábio</option>
                        <option value="Robson">Robson</option>
                        <option value="Outro">Outro</option>
                    </select>
    			</div>
                <div class="form-group">
        		    <label for="cliente_nome">Data</label>
        			<input required type="text" class="form-control calendario" id="saida" name="saida" autocomplete="off">
    			</div>
                <div class="row">
                    <div class="col-md-6 col-sm-6">
        			    <label for="cliente_nome">Hora Saída</label>
        			    <input required type="text" class="form-control time" id="saidah" name="saida_hora" autocomplete="off">
    			    </div>
                    <div class="col-md-6 col-sm-6">
        			    <label for="cliente_nome">Hora Retorno</label>
        			    <input required type="text" class="form-control time" id="retornoh" name="retorno_hora" autocomplete="off">
    			    </div>
    			</div>

    			<div id="cargas_lista"></div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary" id="salvar_cargas">Salvar</button>
				<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
			</div>
		</div>
	</div>
</div>

<link href="/css/select2.min.css" rel="stylesheet" />
<script src="/js/select2.min.js"></script>
<script type="text/javascript">


    $('body').on('focus',".calendario", function(){

        $(this).datepicker({
            dateFormat: 'dd/mm/yy',
            dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'],
            dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
            dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
            monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
            monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
            nextText: 'Próximo',
            prevText: 'Anterior'
        });
    });
    
    $('#saidah').timepicker({
        hourText: 'Hora',
        minuteText: 'Minutos',
        showPeriod: false,
        showPeriodLabels: false,
        interval: 60
    });

    $('#retornoh').timepicker({
        hourText: 'Hora',
        minuteText: 'Minutos',
        showPeriod: false,
        showPeriodLabels: false,

    });


    function proximo(){
        $("#filtros").attr("action", "<?php echo $this->url('pedidos', array('offset' => $this->filtro['next'], 'situacao' => $this->filtro['situacao'])); ?>");
        $("#filtros").submit();
    }

    function anterior(){
        $("#filtros").attr("action", "<?= $this->url('pedidos', array('offset' => $this->filtro['preview'], 'situacao' => $this->filtro['situacao'])); ?>");
        $("#filtros").submit();
    }

    function HabDesmembrar(idvenda){
        $(".qtd_desm_"+idvenda).show();
        $(".btn_desmembrar_"+idvenda).show();
        $(".btn_habilitardesmembrar_"+idvenda).hide();
    }

    function desmembrar(idvenda){
        var produtos = [];
        $(".qtd_desm_"+idvenda).each(function() {
            produtos[$( this ).attr( "id" )] = $( this ).val();
        });

        var jsonString = JSON.stringify(produtos);
        
        $.ajax({
            type: "POST",
            url: "<?php echo $this->url('desmembrar'); ?>",
            data: {prods : jsonString, idvenda : idvenda}, 
            success: function(data) {
                alert('Tramitado com sucesso!');
        	    document.location.reload(true);
            }
        });
    }
    
    $("#carga-modal").on('shown.bs.modal', function(){
	    $.ajax({
            type: "POST",
            url: "<?php echo $this->url('carregarcargas'); ?>",
            success: function(data) {  
        	    $('#cargas_lista').html(data);
            }
        });
    });
    
    $(document).ready( function () {
    
	    $('#cidade').select2();
        $(".time").mask("99:99");

        $("#cpfcnpj").keydown(function(){
        
		    var tamanho = $("#cpfcnpj").val().length;

		    try {
			    $("#cpfcnpj").unmask();
		    } catch (e) {}


		    if(tamanho < 12){
			    $("#cpfcnpj").mask("999.999.999-99");
		    } else {
			    $("#cpfcnpj").mask("99.999.999/9999-99");
		    }

		    // ajustando foco
		    var elem = this;
		    setTimeout(function(){
			    // mudo a posição do seletor
			    elem.selectionStart = elem.selectionEnd = 10000;
		    }, 0);
		    // reaplico o valor para mudar o foco
		    var currentValue = $(this).val();
		    $(this).val('');
		    $(this).val(currentValue);
	    });

        if(<?=$this->filtro['preview'];?> < 0){
           $("#anterior").attr("disabled", "true");
        }

        if("<?php if(isset($this->filtro['limite']) && $this->filtro['limite'] == 0)echo 'todos';?>" == "todos"){
            $("#next").attr("disabled", "true");
            $("#anterior").attr("disabled", "true");

        }

        $('#situacao').change(function(){
            $('#select_carga').val('');
            if($(this).val() == "Carregamento" || ($(this).val() == "Entrega" &&  <?php echo $this->filtro['situacao'] == 'Carregamento' ? 'false' : 'true' ?>)){
                $('#select_carga').attr("disabled", false);
                var temp = $(this).val();
                $("#select_carga option").each(function()
                {
                    if($(this).attr("data-situ") == temp || $(this).val() == ''){
                        $(this).show();
                    }else{
                        $(this).hide();
                    }
                });
            }
            else{
                $('#select_carga').attr("disabled", true);
            }
        });

        $('#salvar_cargas').click(function(){
            if($("#motorista_carga").val() == "" || $("#saida").val() == "" || $("#saidah").val() == ""){
                alert("Todos os campos foram obrigatórios!");
                return false;
            }

	        $.ajax({
                type: "POST",
                data: { 'motorista': $("#motorista_carga").val(),'saida': $("#saida").val(), 'saidah': $("#saidah").val(), 'retornoh': $("#retornoh").val(), 'situacao': $("#situacao_carga").is(':checked') },
                url: "<?php echo $this->url('cadastrarcarga'); ?>",
                success: function(data) {
                    var situacao = $("#situacao_carga").is(':checked') ? 'Entrega' : 'Carregamento';
        	        $('#carga-modal').modal('hide');
        	        $('.modal-backdrop').remove();
        	        $('#select_carga').append($('<option>', {
        	            value: data.trim(),
        	            text: $("#motorista_carga").val() + " - " + $("#saida").val() + " " + $("#saidah").val() + " - " + situacao,
                        'data-situ': situacao
        	        }));
    		        $( "#msg" ).addClass("alert alert-success").text("Carga cadastrada com sucesso!");
                }
            });
        });

        $('#btn_tramitar').click(function(){
            
            var checado=false;
            
            if($('#situacao').val() == ""){
                alert("Selecione a situação!");
            }

            if( ($('#situacao').val() == "Entrega" || $('#situacao').val() == "Finalizados" ) && <?php echo $this->filtro['situacao'] == 'Carregamento' || $this->filtro['situacao'] == 'Entrega' ? 'true' : 'false' ?>){
                if($('#select_carga').val()){
                    alert("Selecione um carregamento!");
                }
                $(".carga_tramitar").each(function(){
                    if($(this).is(':checked'))
                       checado=true;
                });
                if(!checado){
                    alert("Deve ser selecionado alguma carga para entregar!");
                }
            }else{
                $('.item_tramitar').each(function(){
                    if($(this).is(':checked'))
                       checado=true;
                });
                if(!checado){
                    alert("Deve ser selecionado algum pedido para tramitar!");
                }
            }
            
            if(!checado){
                 return false;
            }else{
                $('#tramitar').submit();
            }
        });

        $('body').on('click',".venda", function(){
	        if($(this).hasClass('glyphicon-plus')){
		        $(this).removeClass('glyphicon-plus');
		        $(this).addClass('glyphicon-minus');
    	        var id = "#tabela_prod_"+$(this).attr("id");
    	        $(id).show();

                var id_venda = $(this).attr("id");
                $('.asterisk').each(function(){
                    console.log(id_venda);
                    console.log($(this).attr('data-id'));
                    if($(this).attr('data-id') == id_venda){
                        $(this).hide();
                        $.ajax({
                            type: "GET",
                            url: "<?php echo $this->url('abrir'); ?>"+id_venda+"/",
                            success: function(data) {
                                
                            }
                        });
                    }
                       
                });

	        }else{
		        $(this).removeClass('glyphicon-minus');
		        $(this).addClass('glyphicon-plus');
		        var id = "#tabela_prod_"+$(this).attr("id");
		        $(id).hide();
	        }
        });
        
        $('body').on('click',".carga", function(){
	        if($(this).hasClass('glyphicon-plus')){
		        $(this).removeClass('glyphicon-plus');
		        $(this).addClass('glyphicon-minus');
    	        var id = ".tabela_"+$(this).attr("id");
    	        $(id).show();
	        }else{
		        $(this).removeClass('glyphicon-minus');
		        $(this).addClass('glyphicon-plus');
		        var id = ".tabela_"+$(this).attr("id");
		        $(id).hide();

                var idvenda = $(id).attr("data-id-venda");
                var idv = "#tabela_prod_"+idvenda;
		        $(idv).hide();
	        }
        });

    });

</script>