<style>
    .right {
        text-align: right;
    }
</style>

<?php for ($i = 0; $i < 2; $i++): ?>

    <table class="tg">
        <tr>
            <td class="tg-5wxp">
                <img src="<?= $logo ?>" width="100" height="80">
            </td>
            <td class="tg-9wxp" colspan="2"><strong>CORABRAS</strong></td>
        </tr>

        <tr>
            <td colspan="3"><br><br></td>
        </tr>

        <tr>
            <td class="tg-9yu8" colspan="3"><strong>RECIBO</strong></td>
        </tr>

        <tr>
            <td colspan="3"><br><br></td>
        </tr>

        <tr>
            <td colspan="3">
                Recebemos de <?= $pedido['nome'] ?> a quantia supra algarismada de
                <strong>R$ <?= $valor_total_g ?> (<?= $valor_extenso ?>)</strong>
                referente ao pagamento de telhas de concreto.
            </td>
        </tr>

        <tr>
            <td colspan="3"><br><br></td>
        </tr>
        <?php
        setlocale(LC_TIME, 'pt_BR.UTF-8');
        date_default_timezone_set('America/Sao_Paulo');
        $fmt = new IntlDateFormatter(
            'pt_BR',
            IntlDateFormatter::FULL,
            IntlDateFormatter::NONE,
            'America/Sao_Paulo',
            IntlDateFormatter::GREGORIAN,
            "EEEE, dd 'de' MMMM 'de' yyyy"
        );
        ?>

        <tr>
            <td colspan="3" class="right"><?= $fmt->format(new DateTime()) ?></td>
        </tr>

        <tr>
            <td><strong><?= $qtd_total ?> PEÇAS</strong></td>
            <td colspan="2"><br><br><br><br>______________________________________________________________</td>
        </tr>
    </table>

<?php endfor; ?>